name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  create-release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
      
    - name: Generate changelog
      id: changelog
      run: |
        # Extract version from tag
        VERSION=${GITHUB_REF#refs/tags/}
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        
        # Check if this is the first release (no previous tags)
        if git describe --tags --abbrev=0 HEAD^ 2>/dev/null; then
          # Generate changelog from commits since last tag
          CHANGELOG=$(git log --pretty=format:"- %s" $(git describe --tags --abbrev=0 HEAD^)..HEAD)
        else
          # First release - get all commits
          CHANGELOG=$(git log --pretty=format:"- %s" HEAD)
        fi
        
        echo "changelog<<EOF" >> $GITHUB_OUTPUT
        echo "$CHANGELOG" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT
        
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.changelog.outputs.version }}
        name: WhiteNoise ${{ steps.changelog.outputs.version }}
        body: |
          ## Что нового в версии ${{ steps.changelog.outputs.version }}
          
          ${{ steps.changelog.outputs.changelog }}
          
          ## Скачать
          
          Скачайте готовые сборки из артефактов релиза.
          
          ## Установка
          
          1. Скачайте .ipa файл для iOS
          2. Установите через AltStore или TestFlight
          3. Для macOS скачайте .app файл
          
          ## Изменения
          
          Подробности в [CHANGELOG.md](CHANGELOG.md)
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}